"""
Django settings for osdag_web project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from config.secret_key import get_secret_key
from config.postgres_credentials import get_database_name, get_host, get_password, get_port, get_username
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load .env file automatically if present
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    with open(_env_file, 'r') as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _k, _v = _line.split('=', 1)
                os.environ.setdefault(_k.strip(), _v.strip().strip("'").strip('"'))

# Add project root to Python path for osdag_core imports
# This allows: from osdag_core.design_type.connection.fin_plate_connection import FinPlateConnection
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret_key()
DATABASE_NAME = get_database_name()
DATABASE_USER = get_username()
DATABASE_PASSWORD = get_password()
DATABASE_PORT = get_port()
DATABASE_HOST = get_host()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'


# SECURITY WARNING: DEV ONLY - Never use ['*'] in production!
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# CORS Configuration (DEV ONLY - Allow all origins for LAN testing)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    'http://localhost:5175',
    'http://127.0.0.1:5175',
    'http://192.168.1.9:5173',
    'http://10.104.135.9:5173',
    'http://10.186.46.253:5173'
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']

CORS_ALLOW_HEADERS = ["accept",
                      "authorization",
                      "content-type",
                      "user-agent",
                      "x-csrftoken",
                      "x-requested-with",
                      "x-user-email",
                      'access-control-allow-origin',
                      'Cache-Control',
                      'Pragma',
                      ]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'apps.core.apps.OsdagConfig', 
    'apps.sections.apps.SectionsConfig',  # User-owned custom section catalog (UserCustom*)
    'apps.modules.shear_connection',  # Shear connection parent module
    'apps.modules.moment_connection',  # Moment connection parent module
    'apps.modules.tension_member',  # Tension member parent module
    'apps.modules.flexure_member',  # Flexure member parent module
    # cors headers 
    'corsheaders',

    # DRF
    'rest_framework',
    'silk',
]

# Middleware order is CRITICAL - CorsMiddleware MUST be first
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MUST BE FIRST for CORS to work
    'apps.core.middleware.metrics_middleware.InfluxMetricsMiddleware',  # Metrics (no-op if InfluxDB unavailable)
    'django.middleware.security.SecurityMiddleware',
    'silk.middleware.SilkyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_URL],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
    }
}

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'UTC')
CELERY_TASK_ALWAYS_EAGER = 'test' in sys.argv or any('pytest' in arg for arg in sys.argv)
CELERY_RESULT_EXPIRES = 1800

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'cleanup-temp-files-daily': {
        'task': 'apps.core.tasks.clean_temporary_files',
        'schedule': crontab(hour=0, minute=0),
        'args': (24,),
    },
}


CELERY_DEFAULT_QUEUE = 'calculations'

CELERY_TASK_ROUTES = {
    'apps.core.tasks.run_design_calculation_task': {
        'queue': 'calculations',
    },
    'apps.core.tasks.run_cad_generation_task': {
        'queue': 'cad',
    },
    'apps.core.tasks.run_report_generation_task': {
        'queue': 'reports',
    },
}

# Optional Redis cache backend (toggle with USE_REDIS_CACHE=true)
USE_REDIS_CACHE = os.getenv('USE_REDIS_CACHE', 'false').lower() == 'true'
if USE_REDIS_CACHE:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_CACHE_URL', 'redis://redis:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.core.middleware.firebase_auth.FirebaseAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'apps.core.permissions.IsEmailVerifiedIfAuthenticated',
    ),
    # Used by ScopedRateThrottle on section import/export views only.
    'DEFAULT_THROTTLE_RATES': {
        'sections_import': '60/hour',
        'sections_export': '120/hour',
    },
}


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
_static_dir = BASE_DIR / "static"
STATICFILES_DIRS = [_static_dir] if _static_dir.exists() else []

# OSI files storage
OSIFILES_URL = '/osifiles/'
OSIFILES_ROOT = BASE_DIR / 'osifiles'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SECRET_ROOT = os.path.join(BASE_DIR , 'secret/')
FILE_STORAGE_ROOT = BASE_DIR / 'file_storage'


# ─── InfluxDB observability (load-test metrics) ───────────────────────────────
# All values come from environment variables so the dev compose and production
# configs can differ. They default to values used in docker-compose.yml.
INFLUXDB_URL    = os.getenv('INFLUXDB_URL',    'http://influxdb:8086')
INFLUXDB_TOKEN  = os.getenv('INFLUXDB_TOKEN')
INFLUXDB_ORG    = os.getenv('INFLUXDB_ORG',    'osdag')
INFLUXDB_BUCKET = os.getenv('INFLUXDB_BUCKET', 'osdag_metrics')

# Add this to the bottom of settings.py

import os
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True) # Creates the logs folder if it doesn't exist

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 5, # 5 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
