# Generated by Django 4.2.21 on 2025-06-24 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('module_type', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=100)),
                ('sub_module', models.CharField(blank=True, max_length=100)),
                ('file_path', models.TextField()),
                ('file_content', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProject',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='UserModuleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('module_type', models.CharField(max_length=100)),
                ('sub_module', models.CharField(blank=True, max_length=100)),
                ('activity_type', models.CharField(choices=[('visit', 'Module Visit'), ('design', 'Design Calculation'), ('save', 'Project Save')], max_length=50)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserModuleActivity',
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'module_name', 'module_type', 'sub_module')},
            },
        ),
    ]
