# Generated by Django 4.2.21 on 2025-06-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userproject_usermoduleactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='input_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='last_opened',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
