# Generated by Django 4.2.21 on 2025-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userproject_input_fields_userproject_last_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='calculation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='design_logs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='design_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('input_entered', 'Input Entered'), ('calculating', 'Calculating'), ('completed', 'Completed'), ('error', 'Error')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='userproject',
            name='input_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='output_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
