# Generated by Django 4.2.21 on 2025-07-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_unique_constraint_userproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('module_id', models.CharField(max_length=200)),
                ('module_name', models.CharField(max_length=200)),
                ('input_values', models.JSONField(blank=True, null=True)),
                ('output_values', models.JSONField(blank=True, null=True)),
                ('logs', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Project',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userproject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserModuleActivity',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
