# Generated by Django 5.2.6 on 2025-09-23 12:53

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_alter_userproject_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsiFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/osifiles/', location=pathlib.PureWindowsPath('D:/Coding/FOSSEE/osdag_project/Osdag-web/osifiles')), upload_to='')),
                ('owner_email', models.CharField(blank=True, max_length=200, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'OsiFile',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='input_values',
        ),
        migrations.RemoveField(
            model_name='project',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='module_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='output_values',
        ),
        migrations.AddField(
            model_name='project',
            name='osi_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
