# Generated by Django 4.2.25 on 2025-10-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('core', '0007_osifile_remove_project_input_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inputs_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='module',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='submodule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
