# Generated by Django 4.2.27 on 2026-01-09 15:50

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_project_inputs_json_project_module_project_submodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Link to Django User (username = Firebase UID)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='osifile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/osifiles/', location=pathlib.PurePosixPath('/home/sogalabhi/Osdag-web/osifiles')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.TextField(blank=True, help_text='Firebase UID', unique=True),
        ),
    ]
