# Generated by Django 5.2.11 on 2026-02-23 11:03

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_useraccount_user_alter_osifile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osifile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/osifiles/', location=pathlib.PureWindowsPath('E:/Project/Osdag/Osdag-web/osifiles')), upload_to=''),
        ),
    ]
