# Generated by Django 5.2.11 on 2026-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_osifile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='outputs_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
