# Generated by Django 4.2.30 on 2026-06-14 12:54

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_custommaterials_user_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angles',
            name='lumax',
            field=models.DecimalField(db_column='Iumax', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='angles',
            name='lvmin',
            field=models.DecimalField(db_column='Ivmin', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='osifile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/osifiles/', location=pathlib.PurePosixPath('/Users/varnikumarpatel/Study/Osdag-web/osifiles')), upload_to=''),
        ),
    ]
