# Generated by Django 4.2.30 on 2026-06-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_angles_lumax_alter_angles_lvmin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='osi_file_path',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='allInputValueFiles',
        ),
    ]
