# Generated by Django 4.2.30 on 2026-06-20 06:11

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_design_remove_project_osi_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user requested account deletion', null=True),
        ),
        migrations.AlterField(
            model_name='osifile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/osifiles/', location=pathlib.PurePosixPath('/app/osifiles')), upload_to=''),
        ),
    ]
