# Generated by Django 4.2.30 on 2026-06-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_useraccount_deletion_requested_at_alter_osifile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='deletion_requested_at',
        ),
    ]
