# Generated by Django 3.2.15 on 2023-03-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='current_state',
            field=models.CharField(default='IV', max_length=2),
        ),
        migrations.AddField(
            model_name='design',
            name='input_values',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='cookie_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
