# Generated by Django 3.2.15 on 2023-03-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0002_auto_20230323_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='current_state',
            field=models.BooleanField(default=False),
        ),
    ]
