# Generated by Django 3.2.19 on 2023-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0004_anchor_bolt_angle_pitch_angles_beams_bolt_bolt_fy_fu_channels_chs_columns_equalangle_material_rhs_sh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor_bolt',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
