# Generated by Django 3.2.19 on 2023-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0005_alter_anchor_bolt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor_bolt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='angle_pitch',
            name='S2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='angle_pitch',
            name='S3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bolt',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
