# Generated by Django 3.2.19 on 2023-06-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0007_auto_20230608_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equalangle',
            name='Source',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
