# Generated by Django 3.2.19 on 2023-06-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0010_auto_20230608_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='Type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
