# Generated by Django 3.2.19 on 2023-06-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0011_alter_columns_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='Type',
            field=models.CharField(default='NULL', max_length=100, null=True),
        ),
    ]
