# Generated by Django 3.2.19 on 2023-06-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0012_alter_columns_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angle_pitch',
            name='S1',
            field=models.IntegerField(null=True),
        ),
    ]
