# Generated by Django 3.2.19 on 2023-06-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0014_auto_20230608_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beams',
            name='It',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='beams',
            name='Iw',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='beams',
            name='Type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
