# Generated by Django 3.2.19 on 2023-06-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0015_auto_20230608_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='Type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
