# Generated by Django 3.2.19 on 2023-06-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0016_alter_channels_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels',
            old_name='FlangeScope',
            new_name='FlangeSlope',
        ),
        migrations.AddField(
            model_name='channels',
            name='rz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
