# Generated by Django 3.2.19 on 2023-06-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0018_auto_20230608_0657'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unequalangle',
            table='UnequalAngle',
        ),
    ]
