# Generated by Django 3.2.19 on 2023-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0019_alter_unequalangle_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='input_values',
            field=models.JSONField(blank=True),
        ),
    ]
