# Generated by Django 3.2.19 on 2023-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0020_alter_design_input_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='current_state',
        ),
        migrations.AlterField(
            model_name='design',
            name='input_values',
            field=models.TextField(blank=True),
        ),
    ]
