# Generated by Django 3.2.19 on 2023-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdag', '0021_auto_20230615_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='input_values',
            field=models.JSONField(blank=True),
        ),
    ]
