apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: InfluxDB
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: osdag
      defaultBucket: osdag_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: osdag-super-secret-token
    isDefault: true
    editable: true
